# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd391038d9e7bbb0d42fa6ab9ba8cdfbb823ffb97c30db8ec1c2b53cb049fdd38b9bf4e09fb89b14e6b57eab6921c433dbec719fdfdd84765ef4858b3b6049dd

test:
  secret_key_base: 57cd4588b60b597000f491cd656f05a6cf58fbec739c6122ea807edf478211c39658e7708feba9cf2f2b4cb5174cb6905151000c3cf4a1cc34dfd8ad89bae6bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
